# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ML_blog',
                'doc_host': 'https://dimasmufid.github.io',
                'git_url': 'https://github.com/dimasmufid/ML_blog',
                'lib_path': 'ML_blog'},
  'syms': {'ML_blog.core': {'ML_blog.core.foo': ('core.html#foo', 'ML_blog/core.py')}}}
